---
- name: Pre-install | Check token
  when: influxdb_api.token == None or influxdb_api.token | length != 88
  fail: msg="influxdb_api.token must be valid, given value is '{{ influxdb_api.token }}'"

- name: Pre-install | Ping InfluxDB
  uri:
    url: "{{ influxdb_api.endpoint }}/api/v2/ping"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"
  environment:
    no_proxy: "{{ influxdb_api.endpoint | urlsplit('hostname') }}"
  register: influxdb_ping

- name: Pre-install | Set local facts
  set_fact:
      buckets_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.buckets }}"
      authorizations_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.authorizations }}"
      orgs_endpoint: "{{ influxdb_api.endpoint }}{{ influxdb_ping.json.orgs }}"

- name: Pre-install | Get existing orgs
  uri:
    url: "{{ orgs_endpoint }}"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"
  environment:
    no_proxy: "{{ orgs_endpoint | urlsplit('hostname') }}"
  register: orgs_ws_result

- name: Pre-install | Get existing buckets
  uri:
    url: "{{ buckets_endpoint }}"
    method: GET
    body_format: json
    status_code: 200
    headers:
        Authorization: "Token {{ influxdb_api.token }}"
  environment:
    no_proxy: "{{ buckets_endpoint | urlsplit('hostname') }}"
  register: buckets_ws_result

- name: Pre-install | Set local facts
  set_fact:
      buckets: "{{ buckets_ws_result.json.buckets }}"
      orgs: "{{ orgs_ws_result.json.orgs }}"
...